### ISSUE TITLE
4.4.3: documentation build fails with sphinx 7.1.2

### ISSUE THREAD

**Issue by kloczek** [SELinuxProject/setools#109]
Looks like something is wring
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://multidict.aio-libs.org/en/stable/objects.inv...
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 363, in get_outdated_docs
    towncrier_fragment_paths = _lookup_towncrier_fragments(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 119, in _lookup_towncrier_fragments
    towncrier_config = get_towncrier_config(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/_towncrier.py", line 27, in get_towncrier_config
    return load_config_from_file(str(project_path), str(final_config_path))
  File "/usr/lib/python3.8/site-packages/towncrier/_settings/load.py", line 104, in load_config_from_file
    return parse_toml(directory, config)
  File "/usr/lib/python3.8/site-packages/towncrier/_settings/load.py", line 114, in parse_toml
    raise ConfigError("No [tool.towncrier] section.", failing_option="all")
towncrier._settings.load.ConfigError: No [tool.towncrier] section.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 287, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 381, in read
    for docs in self.events.emit('env-get-outdated', self.env, added, changed, removed):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7ff566bf6a90>> for event 'env-get-outdated' threw an exception (exception: No [tool.towncrier] section.)

Extension error (sphinxcontrib.towncrier.ext):
Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7ff566bf6a90>> for event 'env-get-outdated' threw an exception (exception: No [tool.towncrier] section.)
```
</details>

**Comment by kloczek** [comment]
Ups sorry wrong repo
