### ISSUE TITLE
python3.9 - TypeError: __new__() missing 2 required positional arguments: 'bases' and 'classdict'

### ISSUE THREAD

**Issue by bachradsusi** [SELinuxProject/setools#42]
Fedora Python team started to build tools with Python3.9. SETools builds find with it, but it can't be used due to the following backtrace:

~~~~
# seinfo
Traceback (most recent call last):
  File "/usr/bin/seinfo", line 21, in <module>
    import setools
  File "/usr/lib64/python3.9/site-packages/setools/__init__.py", line 79, in <module>
    from .diff import PolicyDifference
  File "/usr/lib64/python3.9/site-packages/setools/diff/__init__.py", line 37, in <module>
    from .terules import TERulesDifference
  File "/usr/lib64/python3.9/site-packages/setools/diff/terules.py", line 201, in <module>
    class TERulesDifference(Difference):
  File "/usr/lib64/python3.9/site-packages/setools/diff/terules.py", line 208, in TERulesDifference
    diff_allows = av_diff_template("allow")
  File "/usr/lib64/python3.9/site-packages/setools/diff/terules.py", line 71, in av_diff_template
    ruletype = TERuletype.lookup(ruletype)
  File "setools/policyrep/util.pxi", line 59, in setools.policyrep.PolicyEnum.lookup
TypeError: __new__() missing 2 required positional arguments: 'bases' and 'classdict'
~~~~

Originally reported in Fedora bug - https://bugzilla.redhat.com/show_bug.cgi?id=1813076#c2

**Comment by pebenito** [comment]
Seems like it is a cython issue, as `setools.policyrep.PolicyEnum.lookup` is a `@classmethod`. There is no explicit `__new__` method there.

**Comment by bachradsusi** [comment]
Reported on cython  https://bugzilla.redhat.com/show_bug.cgi?id=1788506  https://github.com/cython/cython/issues/3349
