### ISSUE TITLE
setools breaks on defaultrange glblub

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/setools#44]
I noticed that seinfo, sesearch, etc stop working when I have the selinux-testsuite policy loaded and tracked this down to the (defaultrange db_table glblub) statement in the test_glblub.cil module. It appears that support hasn't yet been implemented in setools for glblub.  What is perhaps more surprising is the behavior of setools when encountering this unknown value; it just prints "7" without any explanation or traceback and either provides no other output or only header information (seinfo).  Easy enough to add GLBLUB but not sure about the general handling there.

**Comment by pebenito** [comment]
Ok, I'll look in to it. In general the tools will suppress tracebacks and only return the message from the exception, which unfortunately is not helpful in this case.  Adding `--debug` should report the traceback.

**Comment by pebenito** [comment]
For reference, here's the error:

```
$ seinfo policy-glblub.31 --debug
2020-05-07 10:15:45,594|INFO|setools.policyrep|Opening SELinux policy "policy-glblub.31"
2020-05-07 10:15:45,594|DEBUG|setools.policyrep|Rebuilding attributes.
2020-05-07 10:15:45,594|DEBUG|setools.policyrep|Setting permissive flags in type datums.
2020-05-07 10:15:45,594|DEBUG|setools.policyrep|Creating cat_val_to_struct.
2020-05-07 10:15:45,594|DEBUG|setools.policyrep|Creating level_val_to_struct.
2020-05-07 10:15:45,594|INFO|setools.policyrep|Successfully opened SELinux policy "policy-glblub.31"
Statistics for policy file: policy-glblub.31
Policy Version:             32 (MLS enabled)
Target Policy:              selinux
Handle unknown classes:     deny
Traceback (most recent call last):
  File "setools/policyrep/objclass.pxi", line 109, in setools.policyrep.ObjClass.factory
    return _objclass_cache[policy][<uintptr_t>symbol]
KeyError: 94118923058848

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/seinfo", line 337, in <module>
    p.class_count, p.permission_count))
  File "setools/policyrep/selinuxpolicy.pxi", line 264, in genexpr
    return sum(len(c.perms) for c in itertools.chain(self.commons(), self.classes()))
  File "setools/policyrep/selinuxpolicy.pxi", line 264, in genexpr
    return sum(len(c.perms) for c in itertools.chain(self.commons(), self.classes()))
  File "setools/policyrep/objclass.pxi", line 256, in setools.policyrep.ObjClassHashtabIterator.__next__
    return ObjClass.factory(self.policy, <sepol.class_datum_t *>self.curr.datum)
  File "setools/policyrep/objclass.pxi", line 158, in setools.policyrep.ObjClass.factory
    c._defaults.append(Default.factory(policy, c, None, None, None, symbol.default_range))
  File "setools/policyrep/default.pxi", line 118, in setools.policyrep.Default.factory
    objr._default = DefaultValue.from_default_range(range_)
  File "setools/policyrep/default.pxi", line 47, in setools.policyrep.DefaultValue.from_default_range
    return cls(default_map[range_])
KeyError: 7

```
The first exception should be ignored as that is a cache miss. Second one needs to add a new message for the KeyError.
