### ISSUE TITLE
sechecker - AssertionError: No checks are loaded, this is a bug

### ISSUE THREAD

**Issue by milosmalik** [SELinuxProject/setools#56]
When running `sechecker ./config.ini --debug` command on Fedora Rawhide I get this message:
```
Traceback (most recent call last):
  File "/usr/bin/sechecker", line 49, in <module>
    c = setools.PolicyChecker(p, args.config)
  File "/usr/lib64/python3.9/site-packages/setools/checker/checker.py", line 41, in __init__
    assert CHECKER_REGISTRY, "No checks are loaded, this is a bug."
AssertionError: No checks are loaded, this is a bug.
```

The config.ini file contains the examples from the sechecker man page:
```
[no_unconfined]
check_type = empty_typeattr
desc = Verify that the domain_unconfined_type attribute is missing or empty.
attr = domain_unconfined_type
missing_ok = True

[execheap]
check_type = assert_te
desc = Verify no domains have executable heap.
tclass = process
perms = execheap
exempt_source = unconfined_execheap_t

[ro_execs]
check_type = empty_typeattr
desc = Verify that the all executables and libraries are read-only.
```
What am I doing wrong?
```
# rpm -qa \*setools\* | sort
python3-setools-4.4.0-0.2.20201102git05e90ee.fc34.x86_64
setools-console-4.4.0-0.2.20201102git05e90ee.fc34.x86_64
setools-console-analyses-4.4.0-0.2.20201102git05e90ee.fc34.x86_64
```

**Comment by pebenito** [comment]
Not sure why I can't reproduce this. Can you try adding this to `setools/checker/__init__.py`:
```
from . import assertrbac
from . import assertte
from . import emptyattr
from . import roexec
```

**Comment by milosmalik** [comment]
After adding the 4 `import` lines, the `sechecker` tool works as expected.

**Comment by milosmalik** [comment]
Can you  @bachradsusi make a new build of setools for Fedora Rawhide which contains this change?
