### ISSUE TITLE
Apol TypeError exception when trying to perform any analysis

### ISSUE THREAD

**Issue by stevedlawrence** [SELinuxProject/setools#77]
Running apol from the master branch on a fully updated Fedora 37 with PyQt-5.15.6, I can load a policy and the summary tab shows up as expected, but I get the following exception and abort when selecting `New Analysis` and picking any analysis:

```
TypeError: a member of enum 'StandardKey' is expected not 'QChildEvent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../setools.git/setoolsgui/tableview.py", line 58, in event
    return super(SEToolsTableView, self).event(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'super'> returned a result with an exception set
TypeError: a member of enum 'StandardKey' is expected not 'QChildEvent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../setools.git/setoolsgui/tableview.py", line 58, in event
    return super(SEToolsTableView, self).event(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <class 'super'> returned a result with an exception set
Aborted (core dumped)
```

DTA and Information Flow analyses have a similar error, but with `treeview.py` instead.

**Comment by pebenito** [comment]
The superclass of `SEToolsTreeWidget` is `QTreeWidget`, which is Qt/pyQt, so I can't do anything about it. Please file a F37 bug report for pyQt5.

**Comment by freedom1b2830** [comment]
@pebenito 
no fixed
distr:Arch linux
setools 4.4.0-2 

```
TypeError: a member of enum 'StandardKey' is expected not 'QChildEvent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setoolsgui/treeview.py", line 76, in event
    return super(SEToolsTreeWidget, self).event(e)
SystemError: <class 'super'> returned a result with an exception set
Аварийный останов (стек памяти сброшен на диск)
```
